name = "tldraw-ai-worker"
main = "worker/worker.ts"
compatibility_date = "2024-07-01"

[dev]
port = 5172
ip = "0.0.0.0"

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "TLDRAW_AI_DURABLE_OBJECT", class_name = "TldrawAiDurableObject" },
]

# Durable objects require migrations to create/modify/delete them
[[migrations]]
tag = "v1"
new_classes = ["TldrawAiDurableObject"]

